# Generated by Django 4.2.2 on 2023-08-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_region_alter_address_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
