# Generated by Django 4.2.2 on 2023-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_category_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='food.category'),
        ),
    ]
