# Generated by Django 4.2.2 on 2023-08-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_payment_status_alter_orderitem_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('cardReader', 'cardReader')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('success', 'success'), ('fail', 'fail'), ('loading', 'loading')], max_length=7, null=True)),
                ('bank_gateway', models.CharField(blank=True, choices=[('saman', 'saman'), ('parsian', 'parsian')], max_length=7, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
        ),
    ]
